[flavortown]
triggers=["\\bflavo(u)?rtown\\b"]
priority=1

[ft-voting]
name="flavortown"
info="Related to flavortown voting"
user_autoresponse=":hii: Thank you for your message, we will unlock your votes in about 24-48hr please wait till then."
triggers=["\\bflavo(u)?rtown\\b[\\s\\S]*\\bvoting\\b|\\bvoting\\b[\\s\\S]*\\bflavo(u)?rtown\\b"]
priority=2
